# Generated by Django 5.1.4 on 2024-12-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "addresses",
            "0002_alter_address_options_alter_city_options_city_slug_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name": "Город", "verbose_name_plural": "Города"},
        ),
        migrations.AlterField(
            model_name="city",
            name="region",
            field=models.CharField(
                choices=[
                    ("minsk", "Минская область"),
                    ("grodno", "Гродненская область"),
                    ("vitebsk", "Витебская область"),
                    ("gomel", "Гомельская область"),
                    ("mogilev", "Могилевская область"),
                    ("brest", "Брестская область"),
                ],
                max_length=50,
                verbose_name="Область",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="slug",
            field=models.CharField(max_length=255),
        ),
    ]
