# Generated by Django 5.1.4 on 2024-12-21 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_alter_cart_profile"),
        ("orders", "0003_alter_order_profile"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
