# Generated by Django 5.1.4 on 2024-12-25 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"verbose_name": "Платеж", "verbose_name_plural": "Платежи"},
        ),
    ]
