# Generated by Django 5.1.4 on 2024-12-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.AddField(
            model_name="product",
            name="manufacturer",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="product",
            name="release_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
