# Generated by Django 5.1.4 on 2024-12-25 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_profile_review"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("name",),
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "Профиль", "verbose_name_plural": "Профили"},
        ),
        migrations.AlterModelOptions(
            name="review",
            options={
                "ordering": ("-created",),
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
            },
        ),
    ]
