# Generated by Django 5.1.4 on 2024-12-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_alter_product_options_alter_profile_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="city",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
