# Generated by Django 5.1.4 on 2024-12-25 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0003_alter_city_options_alter_city_region_alter_city_slug"),
        ("shop", "0007_alter_profile_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="addresses.city",
            ),
        ),
    ]
