# Generated by Django 5.1.4 on 2024-12-21 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
        ("shop", "0004_profile_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carts",
                to="shop.profile",
            ),
        ),
    ]
