# Generated by Django 5.1.4 on 2024-12-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "В ожидании"),
                    ("processed", "Обработан"),
                    ("shipped", "Отправлен"),
                    ("delivered", "Доставлен"),
                    ("canceled", "Отменен"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
