# Generated by Django 5.1.4 on 2024-12-27 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0003_alter_city_options_alter_city_region_alter_city_slug"),
        ("orders", "0005_remove_orderitem_price"),
        ("users", "0004_alter_payment_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="addresses.address",
                verbose_name="Адрес",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="payment",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="users.payment",
                verbose_name="Платеж",
            ),
            preserve_default=False,
        ),
    ]
